# Generated by Django 3.1.7 on 2021-05-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='Options',
            field=models.CharField(max_length=100, verbose_name='Contact Us'),
        ),
    ]
