# Generated by Django 3.1.7 on 2021-05-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagemain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('ImageName', models.CharField(max_length=30)),
                ('Price', models.IntegerField(verbose_name='Expected Price')),
                ('contact_us', models.CharField(max_length=100)),
            ],
        ),
    ]
