# Generated by Django 3.1.7 on 2021-05-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_imagemain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=100, verbose_name='information'),
        ),
    ]
