# Generated by Django 3.1.7 on 2021-05-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20210518_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Price',
            field=models.IntegerField(default=-1, verbose_name='Expected Price'),
            preserve_default=False,
        ),
    ]
