# Generated by Django 3.1.7 on 2021-05-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20210518_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='CropName',
            field=models.CharField(default=-1, max_length=100, verbose_name='Crop Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='contact_us',
            field=models.CharField(default=-1, max_length=100, verbose_name='Contact_us'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='Price',
            field=models.IntegerField(verbose_name='Expected Price/Kg'),
        ),
    ]
