# Generated by Django 3.1.7 on 2021-05-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20210518_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Price',
            field=models.CharField(max_length=100, verbose_name='Expected Price'),
        ),
    ]
