# Generated by Django 3.1.7 on 2021-05-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelfrm_app', '0002_auto_20210511_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='Aadhar',
            field=models.IntegerField(),
        ),
    ]
